### ISSUE TITLE
README.md: may be a pointer to tell which git-version it is compared to pug-en?

### ISSUE THREAD

**Issue by LionNatsu** [pugjs/pug-zh-cn#3]

**Comment by TimothyGu** [comment]
Can you elaborate?

**Comment by ForbesLindesay** [comment]
We need something in here (maybe automated) to make it clear which content is out of date.  Ideally we would have some kind of dashboard that would let you see the diff to each file since the corresponding file in pug-zh-cn was last updated.

**Comment by LionNatsu** [comment]
@TimothyGu

> Can you elaborate?

Yes, of course.

@ForbesLindesay

> to make it clear which content is out of date. ... let you see the diff to each file ...

I have an idea, the GitHub's `compare`, for example, when we are at `pug-en@f12bbe6`, put this link here: https://github.com/pugjs/pug-en/compare/f12bbe6...master

But on the other hand, it can't show the date or _how many commits_ the `master` ahead it as well.

Badges is the best one though, there is no badge to show the commit status on https://shields.io/. Maybe we can fork this https://github.com/badges/shields but we need to run another service on the server... Anyways, it just an idea...
